name: dir_walker_ci

on:
  push:
  pull_request:

jobs:
  build:
    name: Rust ${{matrix.channel}}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        channel: [stable]
        os: [ubuntu, macos, windows]
    steps:
    - uses: actions/checkout@v2
    - run: rustup default ${{ matrix.channel }}
    - run: cargo build --verbose --all-targets
    - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt --all -- --check
    - run: cargo clippy --tests --examples